import re
import shutil

from flask import Blueprint, jsonify, render_template, request
from agents.image_gen_service import ImageGenService, OUTPUT_DIR

persona_admin_bp = Blueprint('persona_admin', __name__)


# ------------------------------------------------------------------ #
#  Admin page + image management                                       #
# ------------------------------------------------------------------ #

@persona_admin_bp.route('/persona/admin')
def persona_admin():
    states = []
    if OUTPUT_DIR.exists():
        for p in sorted(OUTPUT_DIR.glob("*.png")):
            stem = p.stem
            if stem.endswith("_hq") or stem.endswith("_uhq") or stem.endswith("_exp"):
                continue
            meta = ImageGenService._read_meta(stem)
            states.append({
                'key':      stem,
                'has_hq':   ImageGenService._hq_path(stem).exists(),
                'has_uhq':  ImageGenService._uhq_path(stem).exists(),
                'has_meta': meta is not None,
                'prompt':   meta.get('scene_prompt', '') if meta else '',
            })
    return render_template('persona_admin.html', states=states)


@persona_admin_bp.route('/persona/requeue/<state>', methods=['POST'])
def requeue_persona_image(state):
    if not re.fullmatch(r'[a-z_]+', state):
        return jsonify({'error': 'Invalid state'}), 400
    tier = request.args.get('tier', 'mq')
    if tier not in ('mq', 'uhq'):
        return jsonify({'error': "tier must be 'mq' or 'uhq'"}), 400
    if not ImageGenService.requeue(state, tier):
        return jsonify({'error': 'No metadata found — image was not generated by this system'}), 404
    return jsonify({'ok': True, 'state': state, 'tier': tier})


@persona_admin_bp.route('/persona/invalidate/<state>', methods=['POST'])
def invalidate_persona_image(state):
    if not re.fullmatch(r'[a-z_]+', state):
        return jsonify({'error': 'Invalid state'}), 400
    tier = request.args.get('tier', 'all')
    if tier not in ('fast', 'mq', 'uhq', 'all'):
        return jsonify({'error': "tier must be 'fast', 'mq', 'uhq', or 'all'"}), 400
    try:
        ImageGenService.invalidate(state, tier)
        return jsonify({'ok': True, 'state': state, 'tier': tier})
    except ValueError as e:
        return jsonify({'error': str(e)}), 404


# ------------------------------------------------------------------ #
#  Memory management                                                   #
# ------------------------------------------------------------------ #

@persona_admin_bp.route('/persona/memories', methods=['GET'])
def get_memories():
    from agents.memory_service import MemoryService
    return jsonify(MemoryService.get_all())


@persona_admin_bp.route('/persona/memories/<int:index>', methods=['DELETE'])
def delete_memory(index):
    from agents.memory_service import MemoryService
    try:
        MemoryService.remove_at(index)
        return jsonify({"ok": True})
    except IndexError as e:
        return jsonify({"error": str(e)}), 404


@persona_admin_bp.route('/persona/memories', methods=['DELETE'])
def clear_memories():
    from agents.memory_service import MemoryService
    MemoryService.clear()
    return jsonify({"ok": True})


# ------------------------------------------------------------------ #
#  Experiment generation                                               #
# ------------------------------------------------------------------ #

@persona_admin_bp.route('/persona/experiment/<state>', methods=['POST'])
def experiment_persona_image(state):
    if not re.fullmatch(r'[a-z_]+', state):
        return jsonify({'error': 'Invalid state'}), 400
    body = request.get_json(silent=True) or {}
    scene_prompt = body.get('scene_prompt', '').strip()
    if not scene_prompt:
        return jsonify({'error': 'scene_prompt required'}), 400
    tier = body.get('tier', 'fast')
    if tier not in ('fast', 'mq', 'uhq'):
        return jsonify({'error': "tier must be 'fast', 'mq', or 'uhq'"}), 400
    seed = body.get('seed')
    if seed is not None:
        try:
            seed = int(seed)
        except (ValueError, TypeError):
            return jsonify({'error': 'seed must be an integer'}), 400
    try:
        result = ImageGenService.generate_experiment(state, scene_prompt, seed=seed, tier=tier)
    except ValueError as e:
        return jsonify({'error': str(e)}), 400
    # fast = synchronous (result is a Path); mq/uhq = queued (result is None)
    return jsonify({'ok': True, 'async': result is None})


@persona_admin_bp.route('/persona/experiment/<state>/commit', methods=['POST'])
def commit_experiment(state):
    if not re.fullmatch(r'[a-z_]+', state):
        return jsonify({'error': 'Invalid state'}), 400
    body = request.get_json(silent=True) or {}
    tier = body.get('tier', 'fast')
    if tier not in ('fast', 'mq', 'uhq'):
        return jsonify({'error': "tier must be 'fast', 'mq', or 'uhq'"}), 400

    exp_path = OUTPUT_DIR / f"{state}_{tier}_exp.png"
    if not exp_path.exists():
        return jsonify({'error': f'No experiment image found for tier {tier}'}), 404

    if tier == 'fast':
        target = OUTPUT_DIR / f"{state}.png"
    elif tier == 'mq':
        target = ImageGenService._hq_path(state)
    else:
        target = ImageGenService._uhq_path(state)

    shutil.copy2(exp_path, target)
    return jsonify({'ok': True})
